# Generated by Django 3.1.3 on 2021-01-03 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=53, unique=True)),
                ('current_balence', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='transfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('send_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='banking_system.customer')),
                ('send_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reciver', to='banking_system.customer')),
            ],
        ),
    ]
