# Generated by Django 3.1.3 on 2021-01-03 10:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 3), null=True),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 3, 10, 56, 19, 556744, tzinfo=utc), null=True),
        ),
    ]
