# Generated by Django 3.1.3 on 2021-01-03 11:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0002_auto_20210103_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 3, 11, 4, 0, 537211, tzinfo=utc), null=True),
        ),
    ]
