# Generated by Django 3.1.3 on 2021-01-04 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0003_auto_20210103_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=datetime.date(2021, 1, 4)),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 4, 7, 23, 13, 148390, tzinfo=utc)),
        ),
    ]
