# Generated by Django 3.1.3 on 2021-01-04 11:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('banking_system', '0004_auto_20210104_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='time',
            field=models.TimeField(default=datetime.datetime(2021, 1, 4, 11, 32, 40, 335563, tzinfo=utc)),
        ),
    ]
